-- ============================================================
-- V002 — Seed categories from kateqoriyalar_final data
-- ============================================================

INSERT INTO categories (item_code, level_1, level_2, level_3, item_name, display_order)
VALUES
('DOC.01.01.01.01', 'Sənədləşmə və Hüquqi', 'Mülkiyyət Sənədləri', 'Torpaq', 'Torpağın çıxarışı (Kupça)', 10),
('DOC.01.01.02.01', 'Sənədləşmə və Hüquqi', 'Mülkiyyət Sənədləri', 'Ev', 'Evin çıxarışı (Kupça)', 20),
('DOC.01.02.01.01', 'Sənədləşmə və Hüquqi', 'Layihə və İcazələr', 'Memarlıq', 'Eskiz layihəsinin çəkilməsi', 30),
('DOC.01.02.02.01', 'Sənədləşmə və Hüquqi', 'Layihə və İcazələr', 'Dövlət İcazələri', 'İcra hakimiyyəti tikinti icazəsi', 40),
('DOC.01.03.01.01', 'Sənədləşmə və Hüquqi', 'Kommunal Şərtlər', 'Elektrik', 'Azərişıq texniki şərt və layihə', 50),
('DOC.01.03.02.01', 'Sənədləşmə və Hüquqi', 'Kommunal Şərtlər', 'Su və Kanalizasiya', 'Azərsu texniki şərt və layihə', 60),
('DOC.01.03.03.01', 'Sənədləşmə və Hüquqi', 'Kommunal Şərtlər', 'Qaz', 'Azəriqaz texniki şərt və layihə', 70),
('DOC.01.04.01.01', 'Sənədləşmə və Hüquqi', 'Hüquqi Xidmətlər', 'Notarius', 'Müqavilələrin təsdiqi və etibarnamələr', 80),
('DOC.01.04.02.01', 'Sənədləşmə və Hüquqi', 'Hüquqi Xidmətlər', 'Dövlət Rüsumları', 'Reyestr xidmət haqları', 90),
('SITE.02.01.01.01', 'Torpaq və Hazırlıq', 'Sahənin Təmizlənməsi', 'Söküntü', 'Köhnə tikililərin sökülməsi', 100),
('SITE.02.01.02.01', 'Torpaq və Hazırlıq', 'Sahənin Təmizlənməsi', 'Tullantı', 'Zibil və yabanı bitkilərin təmizlənməsi', 110),
('SITE.02.02.01.01', 'Torpaq və Hazırlıq', 'Geodeziya', 'Ölçmə', 'Torpaq sərhədlərinin təyini', 120),
('SITE.02.02.02.01', 'Torpaq və Hazırlıq', 'Geodeziya', 'Relyef', 'Topoqrafik xəritəçəkmə', 130),
('SITE.02.03.01.01', 'Torpaq və Hazırlıq', 'Qazıntı İşləri', 'Bünövrə', 'Ekskavatorla bünövrə qazıntısı', 140),
('SITE.02.03.02.01', 'Torpaq və Hazırlıq', 'Qazıntı İşləri', 'Hovuz', 'Hovuz üçün qazıntı', 150),
('SITE.02.04.01.01', 'Torpaq və Hazırlıq', 'Torpaq Daşınması', 'Dolğu', 'Qara torpaq və ya şeben dolğusu', 160),
('SITE.02.04.02.01', 'Torpaq və Hazırlıq', 'Torpaq Daşınması', 'Kənarlaşdırma', 'Artıq torpağın ərazidən çıxarılması', 170),
('SITE.02.05.01.01', 'Torpaq və Hazırlıq', 'Müvəqqəti İnfrastruktur', 'Sığınacaq', 'Fəhlə budkasının (konteyner) qurulması', 180),
('SITE.02.05.02.01', 'Torpaq və Hazırlıq', 'Müvəqqəti İnfrastruktur', 'Kommunal', 'Müvəqqəti elektrik və su xəttinin çəkilişi', 190),
('SITE.02.05.03.01', 'Torpaq və Hazırlıq', 'Müvəqqəti İnfrastruktur', 'Təhlükəsizlik', 'Müvəqqəti hasarlanma', 200),
('STRUCT.03.01.01.01', 'Karkas və Bünövrə', 'Metal Konstruksiya', 'Armatur', 'Müxtəlif diametrli armaturlar (10-16mm)', 210),
('STRUCT.03.01.02.01', 'Karkas və Bünövrə', 'Metal Konstruksiya', 'Bağlama', 'Toxuma teli (Katan)', 220),
('STRUCT.03.02.01.01', 'Karkas və Bünövrə', 'Beton İşləri', 'Material', 'M300 / M350 Hazır beton', 230),
('STRUCT.03.02.02.01', 'Karkas və Bünövrə', 'Beton İşləri', 'Xidmət', 'Beton nasosu icarəsi', 240),
('STRUCT.03.03.01.01', 'Karkas və Bünövrə', 'Hörgü Materialları', 'Daş', 'Mişar daşı (Kubik)', 250),
('STRUCT.03.03.02.01', 'Karkas və Bünövrə', 'Hörgü Materialları', 'Kərpic', 'Arakəsmə kərpicləri', 260),
('STRUCT.03.04.01.01', 'Karkas və Bünövrə', 'Qarışıqlar', 'Sement', 'Sement (M400/M500)', 270),
('STRUCT.03.04.02.01', 'Karkas və Bünövrə', 'Qarışıqlar', 'İnert Materiallar', 'Qum, Şeben, Atsep', 280),
('STRUCT.03.05.01.01', 'Karkas və Bünövrə', 'Qəlib İşləri', 'Opalubka', 'Taxta və ya faner qəliblər', 290),
('STRUCT.03.05.02.01', 'Karkas və Bünövrə', 'Qəlib İşləri', 'Dəstək', 'Metal dirəklər (Dönkrat)', 300),
('STRUCT.03.06.01.01', 'Karkas və Bünövrə', 'İzolyasiya', 'Hidroizolyasiya', 'Ruberoid', 310),
('STRUCT.03.06.02.01', 'Karkas və Bünövrə', 'İzolyasiya', 'Mastika', 'Bitum praymeri və maye izolyasiya', 320),
('ROOF.04.01.01.01', 'Dam Örtüyü', 'Karkas', 'Ağac materialı', 'Dam taxtaları və dikmələr', 330),
('ROOF.04.01.02.01', 'Dam Örtüyü', 'Karkas', 'Bağlayıcılar', 'Mismar və şuruplar', 340),
('ROOF.04.02.01.01', 'Dam Örtüyü', 'Örtük', 'Metal', 'Metalçerepitsa və ya Profnastil', 350),
('ROOF.04.02.02.01', 'Dam Örtüyü', 'Örtük', 'Keramika/Asfalt', 'Şinglas (Yumşaq dam) və ya Keramik çerepitsa', 360),
('ROOF.04.03.01.01', 'Dam Örtüyü', 'İzolyasiya', 'İstilik', 'Daş yunu və ya şüşə yunu', 370),
('ROOF.04.03.02.01', 'Dam Örtüyü', 'İzolyasiya', 'Rütubət', 'Paroisolyasiya membranı', 380),
('ROOF.04.04.01.01', 'Dam Örtüyü', 'Drenaj', 'Novlar', 'Yağış suları üçün üfüqi novlar', 390),
('ROOF.04.04.02.01', 'Dam Örtüyü', 'Drenaj', 'Borular', 'Şaquli su boruları və künclüklər', 400),
('MEP.05.01.01.01', 'Kommunal və Mühəndislik', 'Elektrik', 'Naqillər', 'Daxili və xarici mis kabellər', 410),
('MEP.05.01.02.01', 'Kommunal və Mühəndislik', 'Elektrik', 'Qoruma', 'Avtomatlar və paylayıcı şitlər', 420),
('MEP.05.01.03.01', 'Kommunal və Mühəndislik', 'Elektrik', 'Mexanizm', 'Rozetka və açarların altlıqları', 430),
('MEP.05.02.01.01', 'Kommunal və Mühəndislik', 'Santexnika', 'Boru - Su', 'İsti və soyuq su boruları (PPR)', 440),
('MEP.05.02.02.01', 'Kommunal və Mühəndislik', 'Santexnika', 'Boru - Kanalizasiya', 'Daxili və xarici PVC kanalizasiya boruları', 450),
('MEP.05.02.03.01', 'Kommunal və Mühəndislik', 'Santexnika', 'Avadanlıq', 'Su çəni və Hidrofor motoru', 460),
('MEP.05.03.01.01', 'Kommunal və Mühəndislik', 'İstilik Sistemi', 'Boru', 'İsti döşəmə boruları və kollektorlar', 470),
('MEP.05.03.02.01', 'Kommunal və Mühəndislik', 'İstilik Sistemi', 'Cihazlar', 'Kombi aparatı və radiatorlar', 480),
('MEP.05.04.01.01', 'Kommunal və Mühəndislik', 'Qaz', 'Xətt', 'Dəmir qaz boruları və vintillər', 490),
('MEP.05.04.02.01', 'Kommunal və Mühəndislik', 'Qaz', 'Sayğac', 'Qaz sayğacı və qutu', 500),
('MEP.05.05.01.01', 'Kommunal və Mühəndislik', 'Havalandırma', 'Kanallar', 'Plastik və ya qalay havalandırma boruları', 510),
('MEP.05.05.02.01', 'Kommunal və Mühəndislik', 'Havalandırma', 'Motorlar', 'Aktiv aspirator və ventilyatorlar', 520),
('FACADE.06.01.01.01', 'Fasad', 'İzolyasiya', 'İstilik qoruma', 'Fasad daş yunu və ya penoplas', 530),
('FACADE.06.02.01.01', 'Fasad', 'Üzlüklər', 'Təbii daş', 'Ağlay daşı', 540),
('FACADE.06.02.02.01', 'Fasad', 'Üzlüklər', 'Dekorativ', 'Tarovka və ya dekorativ suvaq', 550),
('FACADE.06.03.01.01', 'Fasad', 'Boya', 'Astar', 'Fasad qruntu', 560),
('FACADE.06.03.02.01', 'Fasad', 'Boya', 'Son qat', 'Suya/günəşə davamlı xarici boya', 570),
('FACADE.06.04.01.01', 'Fasad', 'İşıqlandırma', 'Cihazlar', 'Divar aplikləri və spot işıqlar', 580),
('DOORS.07.01.01.01', 'Qapı və Pəncərə', 'Xarici Pəncərələr', 'Profil', 'PVC və ya Alüminium profillər', 590),
('DOORS.07.01.02.01', 'Qapı və Pəncərə', 'Xarici Pəncərələr', 'Şüşə', 'İkiqat/Üçqat şüşəpaketlər', 600),
('DOORS.07.01.03.01', 'Qapı və Pəncərə', 'Xarici Pəncərələr', 'Aksesuarlar', 'Ağcaqanad torları və mərmər altlıqlar', 610),
('DOORS.07.02.01.01', 'Qapı və Pəncərə', 'Qapılar', 'Əsas Giriş', 'Dəmir/Seyf qapı', 620),
('DOORS.07.02.02.01', 'Qapı və Pəncərə', 'Qapılar', 'Daxili', 'Otaq və sanuzel üçün MDF/Taxta qapılar', 630),
('DOORS.07.03.01.01', 'Qapı və Pəncərə', 'Qaraj', 'Sistem', 'Avtomatik qaldırıcı jalyuz və mühərrik', 640),
('INTERIOR.08.01.01.01', 'Daxili Təmir', 'Divar Hazırlığı', 'Suvaq', 'Qum-sement və ya gips suvaq (Ağdağ, Qaradağ)', 650),
('INTERIOR.08.01.02.01', 'Daxili Təmir', 'Divar Hazırlığı', 'Şpatlyovka', 'Üz və astar şpatlyovka materialları', 660),
('INTERIOR.08.02.01.01', 'Daxili Təmir', 'Tavan', 'Konstruksiya', 'Alçipan və metal profillər', 670),
('INTERIOR.08.02.02.01', 'Daxili Təmir', 'Tavan', 'Alternativ', 'Dartma tavan materialları', 680),
('INTERIOR.08.03.01.01', 'Daxili Təmir', 'Döşəmə', 'Örtük', 'Laminat və ya Parket', 690),
('INTERIOR.08.03.02.01', 'Daxili Təmir', 'Döşəmə', 'Aksesuarlar', 'Padloşka və plintus (süpürgəlik)', 700),
('INTERIOR.08.04.01.01', 'Daxili Təmir', 'Divar Dekorasiyası', 'Oboy', 'Divar kağızları və yapışdırıcı', 710),
('INTERIOR.08.04.02.01', 'Daxili Təmir', 'Divar Dekorasiyası', 'Boya', 'Daxili məkan üçün yuyula bilən boyalar', 720),
('INTERIOR.08.05.01.01', 'Daxili Təmir', 'Pilləkən', 'Karkas', 'Beton və ya metal pilləkən konstruksiyası', 730),
('INTERIOR.08.05.02.01', 'Daxili Təmir', 'Pilləkən', 'Üzlük', 'Taxta pillələr və sürahilər (perila)', 740),
('BATHROOM.09.01.01.01', 'Sanuzel və Hamam', 'Örtüklər', 'Kafel', 'Divar kafeli', 750),
('BATHROOM.09.01.02.01', 'Sanuzel və Hamam', 'Örtüklər', 'Metlax', 'Döşəmə metlaxı və ya keramoqranit', 760),
('BATHROOM.09.01.03.01', 'Sanuzel və Hamam', 'Örtüklər', 'Qarışıqlar', 'Kafel yapışdırıcısı və derz (fuka)', 770),
('BATHROOM.09.02.01.01', 'Sanuzel və Hamam', 'Santexnika Cihazları', 'Unitaz', 'Asma unitaz və gizli instalyasiya', 780),
('BATHROOM.09.02.02.01', 'Sanuzel və Hamam', 'Santexnika Cihazları', 'Duş/Vanna', 'Duş kabinası və ya vanna', 790),
('BATHROOM.09.02.03.01', 'Sanuzel və Hamam', 'Santexnika Cihazları', 'Moydodır', 'Əlüzyuyan və alt dolabı', 800),
('BATHROOM.09.03.01.01', 'Sanuzel və Hamam', 'Armaturlar', 'Kranlar', 'İsti/soyuq su mikserləri', 810),
('BATHROOM.09.03.02.01', 'Sanuzel və Hamam', 'Armaturlar', 'Duş sistemi', 'Baş duş dəsti və gigiyenik duş', 820),
('BATHROOM.09.04.01.01', 'Sanuzel və Hamam', 'Aksesuarlar', 'Mebel', 'Güzgülü üst dolablar və asılqanlar', 830),
('YARD.10.01.01.01', 'Həyət və Hovuz', 'Giriş', 'Darvaza', 'Əsas dəmir darvaza və avtomatika mühərriki', 840),
('YARD.10.02.01.01', 'Həyət və Hovuz', 'Yollar və Səkilər', 'Örtük', 'Tamet və ya qranit daşlar', 850),
('YARD.10.02.02.01', 'Həyət və Hovuz', 'Yollar və Səkilər', 'Bordür', 'Kənar səki daşları', 860),
('YARD.10.03.01.01', 'Həyət və Hovuz', 'Yaşıllaşdırma', 'Bitkilər', 'Qazon, dekorativ ağaclar və kollar', 870),
('YARD.10.03.02.01', 'Həyət və Hovuz', 'Yaşıllaşdırma', 'Suvarma', 'Avtomatik damlama və ya fısqırtma sistemi', 880),
('YARD.10.04.01.01', 'Həyət və Hovuz', 'Hovuz', 'Konstruksiya', 'Hovuzun betonlanması və hidroizolyasiyası', 890),
('YARD.10.04.02.01', 'Həyət və Hovuz', 'Hovuz', 'Örtük', 'Mozaika və ya hovuz kafeli', 900),
('YARD.10.04.03.01', 'Həyət və Hovuz', 'Hovuz', 'Avadanlıq', 'Filtr, nasos, xlorator və işıqlandırma', 910),
('YARD.10.05.01.01', 'Həyət və Hovuz', 'İstirahət Zonası', 'Besedka', 'Söhbətgah (Çardaq) materialları', 920),
('YARD.10.05.02.01', 'Həyət və Hovuz', 'İstirahət Zonası', 'Manqal', 'Kərpic manqal və tüstü bacası', 930),
('YARD.10.06.01.01', 'Həyət və Hovuz', 'İnfrastruktur', 'Quyu', 'Subartezian quyusunun qazılması', 940),
('YARD.10.06.02.01', 'Həyət və Hovuz', 'İnfrastruktur', 'İşıq', 'Həyət dirək fənərləri', 950),
('SECURITY.11.01.01.01', 'Təhlükəsizlik və İT', 'Müşahidə', 'Kameralar', 'IP/Analoji CCTV kameralar', 960),
('SECURITY.11.01.02.01', 'Təhlükəsizlik və İT', 'Müşahidə', 'Qeydiyyat', 'NVR/DVR cihazı və HDD yaddaş', 970),
('SECURITY.11.02.01.01', 'Təhlükəsizlik və İT', 'Siqnalizasiya', 'Sensorlar', 'Hərəkət, sınma və qapı sensorları', 980),
('SECURITY.11.02.02.01', 'Təhlükəsizlik və İT', 'Siqnalizasiya', 'Yanğın', 'Tüstü və qaz sızması detektorları', 990),
('SECURITY.11.03.01.01', 'Təhlükəsizlik və İT', 'Şəbəkə', 'Kabel', 'CAT6 internet naqilləri', 1000),
('SECURITY.11.03.02.01', 'Təhlükəsizlik və İT', 'Şəbəkə', 'Avadanlıq', 'Router, Switch və Access Point-lər', 1010),
('SECURITY.11.04.01.01', 'Təhlükəsizlik və İT', 'Giriş Nəzarəti', 'Domofon', 'Kameralı domofon paneli və daxili ekran', 1020),
('SECURITY.11.04.02.01', 'Təhlükəsizlik və İT', 'Giriş Nəzarəti', 'Kilid', 'Elektron qapı kilidi', 1030),
('SECURITY.11.05.01.01', 'Təhlükəsizlik və İT', 'Ağıllı Ev', 'İdarəetmə', 'Mərkəzi hab, ağıllı relelər və klapanlar', 1040),
('LABOR.12.01.01.01', 'İşçilik', 'Karkas və Hörgü', 'Bənna', 'Beton, armatur və hörgü ustası haqqı', 1050),
('LABOR.12.02.01.01', 'İşçilik', 'Dam', 'Dülgər', 'Damın karkasını və örtüyünü vuran usta', 1060),
('LABOR.12.03.01.01', 'İşçilik', 'Təmir', 'Malyar', 'Suvaq, şpatlyovka və rəng ustası', 1070),
('LABOR.12.03.02.01', 'İşçilik', 'Təmir', 'Alçipançı', 'Tavan konstruksiyasını yığan usta', 1080),
('LABOR.12.03.03.01', 'İşçilik', 'Təmir', 'Döşəməçi', 'Laminat/parket vuran usta', 1090),
('LABOR.12.04.01.01', 'İşçilik', 'Sanuzel', 'Kafelçi', 'Kafel və metlax ustası', 1100),
('LABOR.12.05.01.01', 'İşçilik', 'Mühəndislik', 'Santexnik', 'Boru və cihazları quraşdıran usta', 1110),
('LABOR.12.05.02.01', 'İşçilik', 'Mühəndislik', 'Elektrik', 'Naqilləşmə və şitləri yığan usta', 1120),
('LABOR.12.06.01.01', 'İşçilik', 'Köməkçi', 'Fəhlə', 'Gündəlik ağır fiziki işləri görən işçilər', 1130),
('TRANSPORT.13.01.01.01', 'Nəqliyyat və Logistika', 'Yük Daşıma', 'Material çatdırılması', 'Tikinti materiallarının mağazadan sahəyə gətirilməsi', 1140),
('TRANSPORT.13.02.01.01', 'Nəqliyyat və Logistika', 'Ağır Texnika', 'Kran', 'Ağır yüklərin qaldırılması üçün kran icarəsi', 1150),
('TRANSPORT.13.02.02.01', 'Nəqliyyat və Logistika', 'Ağır Texnika', 'Manipulyator', 'Paletlərin daşınması və boşaldılması', 1160),
('TRANSPORT.13.03.01.01', 'Nəqliyyat və Logistika', 'Tullantı İdarəetməsi', 'Zibil daşıma', 'Tullantıların poliqona atılması', 1170),
('OTHER.14.01.01.01', 'Digər Xərclər', 'Sərfiyyat', 'Alətlər', 'Laqonda diski, mismar, burğu uçları', 1180),
('OTHER.14.01.02.01', 'Digər Xərclər', 'Sərfiyyat', 'Avadanlıq', 'Vedrə, fırça, bel, əl arabası', 1190),
('OTHER.14.02.01.01', 'Digər Xərclər', 'Ehtiyat', 'Fors-major', 'Nəzərdə tutulmayan əlavə xərclər', 1200),
('EQUIPMENT.15.01.01.01', 'Texnika, Avadanlıq və İcarə', 'Ağır Texnika (Torpaq və Söküntü)', 'Ekskavator və Qırıcılar', 'Ekskavator-çəkic (Qayaları dağıtmaq üçün hidravlik qırıcı)', 1210),
('EQUIPMENT.15.01.01.02', 'Texnika, Avadanlıq və İcarə', 'Ağır Texnika (Torpaq və Söküntü)', 'Ekskavator və Qırıcılar', 'Standart Ekskavator (Torpaq qazıntısı üçün)', 1220),
('EQUIPMENT.15.01.02.01', 'Texnika, Avadanlıq və İcarə', 'Ağır Texnika (Torpaq və Söküntü)', 'Həmvarlama və Yükləmə', 'Buldozer və Bobcat (Sahənin düzləşdirilməsi)', 1230),
('EQUIPMENT.15.01.03.01', 'Texnika, Avadanlıq və İcarə', 'Ağır Texnika (Torpaq və Söküntü)', 'Daşıma Texnikası', 'Özüboşaldan yük maşını (Kamaz / Shacman)', 1240),
('EQUIPMENT.15.02.01.01', 'Texnika, Avadanlıq və İcarə', 'Ağır Texnika (Qaldırıcı və Quraşdırıcı)', 'Kranlar', 'Avtokran (Ağır konstruksiyaların və ya ağacların qaldırılması)', 1250),
('EQUIPMENT.15.02.02.01', 'Texnika, Avadanlıq və İcarə', 'Ağır Texnika (Qaldırıcı və Quraşdırıcı)', 'Səbətli Qaldırıcılar', 'Səbətli kran (İnsanların yüksəkliyə qaldırılması, fasad işləri)', 1260),
('EQUIPMENT.15.02.03.01', 'Texnika, Avadanlıq və İcarə', 'Ağır Texnika (Qaldırıcı və Quraşdırıcı)', 'Özüyükləyən', 'Manipulyator (Materialların boşaldılması və daşınması)', 1270),
('EQUIPMENT.15.03.01.01', 'Texnika, Avadanlıq və İcarə', 'Ağır Texnika (Beton İşləri)', 'Töküm Texnikası', 'Beton nasosu / Pompası (Mərtəbələrə beton vurmaq üçün)', 1280),
('EQUIPMENT.15.03.02.01', 'Texnika, Avadanlıq və İcarə', 'Ağır Texnika (Beton İşləri)', 'Qarışdırıcılar', 'Beton mikseri maşını', 1290),
('EQUIPMENT.15.04.01.01', 'Texnika, Avadanlıq və İcarə', 'Alət və Mexanizm İcarəsi', 'Söküntü və Qazma', 'Perforator və Otboynik (Ağır söküntü çəkicləri)', 1300),
('EQUIPMENT.15.04.02.01', 'Texnika, Avadanlıq və İcarə', 'Alət və Mexanizm İcarəsi', 'Kəsim Alətləri', 'Beton kəsən, Asfalt kəsən, Böyük Laqonda', 1310),
('EQUIPMENT.15.04.03.01', 'Texnika, Avadanlıq və İcarə', 'Alət və Mexanizm İcarəsi', 'Sıxlaşdırıcılar', 'Torpaq kipləşdirən (Vibroplitka) və Beton vibratoru', 1320),
('EQUIPMENT.15.04.04.01', 'Texnika, Avadanlıq və İcarə', 'Alət və Mexanizm İcarəsi', 'Enerji və Təzyiq', 'Generator və Hava kompressoru icarəsi', 1330),
('EQUIPMENT.15.05.01.01', 'Texnika, Avadanlıq və İcarə', 'İnventar və Köməkçi Qurğular', 'Yüksəklik İşləri', 'İskələ sistemləri (Lesa / Scaffolding) icarəsi', 1340),
('EQUIPMENT.15.05.02.01', 'Texnika, Avadanlıq və İcarə', 'İnventar və Köməkçi Qurğular', 'Qəlib Sistemləri', 'Opalubka, faner və metal dirəklərin (dönkrat) icarəsi', 1350)
ON CONFLICT (item_code) DO NOTHING;
